import { Palette } from "../style.slint";

export component Button inherits Rectangle {
    in property <string> text;
    in property <color> font-color: Palette.font-color;
    in property <length> font-size: self.height * 0.3;
    in property <bool> rounded: false;

    in property <color> color-background: Palette.g-color;
    in property <color> color-hover: Palette.dark-mode ? color-background.darker(0.2) : color-background.brighter(0.2);
    in property <color> color-pressed: color-background;

    private property <bool> checkable: false;
    private property <bool> checked: false;

    callback clicked;

    background: color-background;
    
    Text {
        horizontal-alignment: center;
        vertical-alignment: center;
        width: parent.width;
        height: parent.height;
        text: parent.text;
        color: parent.font-color;
        font-size: parent.font-size;
    }

    i-touch-area := TouchArea {
        clicked => {
            if (root.checkable) {
                root.checked = !root.checked;
            }
            root.clicked();
        }
    }

    states [
        pressed when i-touch-area.pressed : {
            background: color-pressed;
        }

        hover when i-touch-area.has-hover : {
            background: color-hover;
        }
    ]
}